report_sizes: true

builds:
  # https://goreleaser.com/customization/build/
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -w -s
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  # https://goreleaser.com/customization/archive/
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: "checksums.txt"

release:
  # https://goreleaser.com/customization/release/
  target_commitish: "{{ .Commit }}"
  mode: replace
  header: |
    ## ℹ️ For information on how to install and use please see `README.md`
  footer: |
    Your PRs & issues are welcome! Thanks 😉
  disable: false
  skip_upload: false

changelog:
  # https://goreleaser.com/customization/changelog/
  sort: asc
